### ISSUE TITLE
Jafu has tangle

### ISSUE THREAD

**Issue by poutsma** [spring-projects/spring-fu#126]
Currently, there is a circular dependency between o.s.fu.jafu and its sub packages. The reason for this tangle is that the `ConfigurationDsl` has the role of a God Configuration Object, with connections to every other configuration. Even though this is very convenient, it is not very maintainable: there are simply too many possible configurations to hook them all together in one object.

**Comment by sdeleuze** [comment]
I tend to agree, Kotlin has [extensions](https://kotlinlang.org/docs/reference/extensions.html) which allow nice syntax with good maintainability, but in Java we probably need to handle things in a different way to avoid god object, and make Jafu extensible.

This could maybe be fixed by using a generic method like `public <D extends AbstractDsl> ConfigurationDsl enable(Consumer<D> dsl)` in `ConfigurationDsl` to allow using various DSL without hardcoding everything.

Any thoughts?

**Comment by sdeleuze** [comment]
@poutsma Could you please have a look to https://github.com/spring-projects/spring-fu/commit/fix-tangle and say me if that's a reasonable fix for the issue your raised?

**Comment by sdeleuze** [comment]
Fixed via an updated version of the commit using static methods.
