### ISSUE TITLE
Support for @Qualifier

### ISSUE THREAD

**Issue by cristianoperez** [spring-projects/spring-fu#148]
Is there any way to use `@Qualifier` with `bean{}` declaration? I couldn't found any way to declare a bean with Qualifier

**Comment by sdeleuze** [comment]
Hey, thanks for your question.

I don't think we should expose qualifier as a first class concept in the functional bean definition model, bean names should IMO used instead, and this is very well supported in current API. For example `bean<UserHandler>("userHandler")` for the definition and `ref<UserHandler>("userHandler")` for retrieving a bean.

Notice that `BeanFactoryAnnotationUtils.qualifiedBeansOfType` introduced via https://github.com/spring-projects/spring-framework/issues/13532 allows to get bean names from qualifier if really needed, mainly for compatibility reasons with JavaConfig, but I can't think of a use case where declaring the qualifier would be needed in a functional world.

What would be your use case?

**Comment by cristianoperez** [comment]
Hey thanks for the aswser, i was migrating as small project, just for learning/testing purpose. Instead of migrate the entier application a migrated just the `@Bean` definitions.

That application happens to have 2 ObjectMappers, something like 

```
@Qualifier
@Bean
fun noRootMapper(): ObjectMapper {
   ...
}

@Primary
@Bean
fun jacksonObjectMapper(builder: Jackson2ObjectMapperBuilder): ObjectMapper {
   ...
}
```
Gets converted to
```
fun beans() = beans {
  bean(isPrimary = true) { jacksonObjectMapper(
  bean(name = "noRootMapper"){ noRootMapper() }
}

fun main(args: Array<String>) {
    runApplication<BanquinhoApplication> {
        addInitializers(beans())
    }
}
```

But when a try to use the `noRootMapper` in the vanilla way, spring injects the wrong mapper

```
class AmazonKinesisFirehoseClientFactory(
        @Value("\${aws.region}")
        private var awsRegion: String,
        @Autowired
        private var noRootMapper: ObjectMapper
)
```

**Comment by sdeleuze** [comment]
As explained by Juergen Hoeller in https://github.com/spring-projects/spring-framework/issues/13532, qualifier is not supported in functional bean registration on purpose, so the kind of issues is indeed expected when mixing annotation and functional bean registration. Our focus, at least for now, is to provide a clean and simple model for functional bean registration rather than feature parity between 2 models.

That said, I don't think your constructor parameter `@Autowired` is actually used, I think `AmazonKinesisFirehoseClientFactory` is autowired because it has a single constructor. Maybe you can try to explicitly specify a `@Qualifier` on  `private var noRootMapper: ObjectMapper` and see if that works in both model with that?
