### ISSUE TITLE
Add support for reusable conditions

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#45]
Maybe something on Spring Framework side, or directly `typealias Condition = (ApplicationContext) -> Boolean` on Spring Fu side. Conditions should be reused in Spring Fu internals and available to the users as well.

**Comment by sdeleuze** [comment]
After more thoughts, not sure that makes sense since functional configuration is based on `ApplicationContextInitializer` (which is in fact `(ConfigurableApplicationContext) -> Unit`) that can register from 0 to n beans with custom registration and bean retrieval logics rather than a model individual bean conditional registration like in annotation world.

**Comment by jeffzoch** [comment]
@sdeleuze I know this is an old issue but I was just trying to work around converting @ConditionalOnClass or @ConditionalOnBean to functional registrations and saw this issue. Is your recommendation, based on your above comment, to add the conditionals around the context initialization rather than the bean registration?
aka instead of 
```kotlin
beans {
  if(exists(bean<Foo>()) bean<Bar>() //made up syntax for conditionalOnBean
  if(classExists<Baz>()) bean<Bop>() //made up syntax for conditionalOnClass
}
```
you suggest:
```kotlin
GenericApplicationContext().apply {
  initialize(firstBeans)
  refresh()
}
if(GenericApplicationContext().containsBean("Foo")) GenericApplicationContext().apply {
  initialize(
  beans {
    bean<Foo>()
  }
)
  refresh()
}
//etc

**Comment by sdeleuze** [comment]
No I think `if` statement are fine inside `beans { }` as shown in your first sample.
