### ISSUE TITLE
README getting started: 

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-fu#74]
I'd love to be able to get down to something like this as the `getting started`:

```
fun main(args: Array<String>) =
    val app = application {
        routes {
            GET("/", () -> { ok().body("Hello, World.") })
        }
    }

    app.run()
```

Which would assume a few things as default arguments:

```
fun main(args: Array<String>) =
    val app = application {
        server(netty(port=8080))

        routes {
            GET("/", () -> { ok().body("Hello, World.") })
        }
    }

    app.run()
```

Rather than having to nest the routes under the server.

**Comment by sdeleuze** [comment]
One of the Spring Fu core value is that features are enabled explicitly instead of relying on classpath detection for example, so even if that's shorter I am not sure that your proposal would be consistent with that principle.

**Comment by berlin-ab** [comment]
What do you think about de-nesting the call to routes from within server to outside of server? It seems like they should be independent.

**Comment by sdeleuze** [comment]
Routes belong to a server, so I think they are at the right place. I am not sure if this is supported yet but you should be able to start multiple servers on different port.

**Comment by berlin-ab** [comment]
Well, that'll be a pretty cool feature. Good point.

**Comment by sdeleuze** [comment]
Could I close this issue?

**Comment by berlin-ab** [comment]
Yes, thanks.

**Comment by sdeleuze** [comment]
After more thoughts, and even if that's technically possible I think it is better to stick with one server per app since that allow easier configuration, and it will be a better fit for integrating Boot. If multiple servers are needed, developers should create multiple applications, we are in the context of Microservices after all.

The current structure (codec and routes belong to a server) reflect the underlying model and should be keep as they are IMO.
